### ISSUE TITLE
please: one step take all 大神们，一步到位啊。

### ISSUE THREAD

**Issue by yuedajiong** [NUS-HPC-AI-Lab/Neural-Network-Diffusion#1]
one step take all:

way 1: offline/explicit
1. 4d (time+stereo) strong physical stereo-consistent, any camera pose, offline render, interactive semantic highly-controllable，world.

OR

way 2: online/implicit
binocular stereo-consistent generate, observe pose in-place change, online realtime, interactive semantic highly-controllable，world.
and: the technical path is: train by binocular-video in Unreal Engine or Physical World.

你们团队很强，有能力做到这种效果。
视觉游戏的终局。

你们这个项目，直接用在立体/双目场景上就可以了。

**Comment by happydummy** [comment]
Can you explain this in more detail?
