### ISSUE TITLE
i want to know why set len(param)==10 here?

### ISSUE THREAD

**Issue by freja-zy** [NUS-HPC-AI-Lab/Neural-Network-Diffusion#21]
i want to know why set len(param)==10 here?

if i > = epoch:
      parameters.append(state_part(train_layer, net))
      save_model_accs.append(acc)
      if len(parameters) == 10 or i == all_epoch - 1:
          torch.save(parameters, os.path.join(tmp_path, "p_data_{}.pt".format(i)))
          parameters = []

**Comment by 1zeryu** [comment]
To avoid storing too many models in one file, we set a maximum of 10 model parameters in one file. This is not a very important detail, you can also set this storage interval to 100
