### ISSUE TITLE
No module named 'core.system.explore'

### ISSUE THREAD

**Issue by ansj11** [NUS-HPC-AI-Lab/Neural-Network-Diffusion#3]
I am running the demo code bash cifar100_resnet18_k200.sh, but i get ModuleNotFoundError: No module named 'core.system.explore'. Is there missing Neural-Network-Diffusion/core/system/explore.py?

**Comment by 1zeryu** [comment]
The explore.py file is the one we used during the exploration of p-diff, and it has already been deleted here. The bug in code core/system/__init__.py
`from .base import *
from .ddpm import *
from .encoder import *
from .vae import VAESystem
from .ae_ddpm import AE_DDPM
from .explore import Explore

systems = {
    'encoder': EncoderSystem,
    'ddpm': DDPM,
    'vae': VAESystem,
    'ae_ddpm': AE_DDPM,
    'explore': Explore,
}`

should change to (just delete explore)

`
from .base import *
from .ddpm import *
from .encoder import *
from .vae import VAESystem
from .ae_ddpm import AE_DDPM

systems = {
    'encoder': EncoderSystem,
    'ddpm': DDPM,
    'vae': VAESystem,
    'ae_ddpm': AE_DDPM,
}`

Thanks for the feedback.
