### ISSUE TITLE
Question about motivation

### ISSUE THREAD

**Issue by ChongQingNoSubway** [NUS-HPC-AI-Lab/Neural-Network-Diffusion#4]
Hello!! Thank you for revealing a good project.

Is the diffusion phenomenon limited only to SGD?  Will the code related to your Figure 1 be released?

Thanks

**Comment by 1zeryu** [comment]
Thanks for your feedback.
We will try other optimizer, e.g, Adam. 
Meanwhile, you can change the config file in configs/task dir.
For example, the optimizer in config/task/cifar100.yaml
`optimizer:
  _target_: torch.optim.SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005`
can change to (Adam optimizer)
`optimizer:
  _target_: torch.optim.Adam
  lr: 0.1
  weight_decay: 0.0005`.
We will run related experiments and are more than willing to share our results!
If you have any question, feel free to ask us.

**Comment by ChongQingNoSubway** [comment]
Thanks
