### ISSUE TITLE
unrecognized arguments: --task --system ae_ddpm

### ISSUE THREAD

**Issue by ansj11** [NUS-HPC-AI-Lab/Neural-Network-Diffusion#6]
I am running python train_p_diff.py --task cifar100 --system ae_ddpm, but get following error

usage: train_p_diff.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--resolve] [--package PACKAGE] [--run] [--multirun] [--shell-completion] [--config-path CONFIG_PATH] [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR]
                       [--experimental-rerun EXPERIMENTAL_RERUN] [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
                       [overrides [overrides ...]]
train_p_diff.py: error: unrecognized arguments: --task --system ae_ddpm

**Comment by 1zeryu** [comment]
We load config file using 'hydra' package.
The override must using '=',
so you can change your command to 
`python train_p_diff.py task=cifar100 system=ae_ddpm`,
If you have any questions feel free to ask us!

**Comment by ansj11** [comment]
Thank you very much, I can run the code successifully!
